# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFamilyErBao' do
  use_frameworks!

pod 'SnapKit'
pod 'Alamofire'
pod 'TZImagePickerController'
pod 'MWTableViewUnit', :git=>'https://git.coding.net/iliunian/MWTableViewUnit.git'
pod 'SQLCipher'

end
